# Generated by Django 2.2.2 on 2019-06-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=models.ManyToManyField(blank=True, to='movie.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
